<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Item::firstOrCreate(['name' => "Rylai's Crystal Scepter", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => true, 'dash' => false, 'poke' => true, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 6, 'is_good_against_magic_damage' => 9, 'is_good_against_shield' => 5, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 7, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 6, 'is_good_against_dash' => 4, 'is_good_against_poke' => 7, 'is_good_against_can_one_shot' => 5, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/4/46/Rylai%27s_Crystal_Scepter_item.png"]);

        Item::firstOrCreate(['name' => "Shurelya's Battlesong", 'role' => "supp", 'attack_damage' => false, 'magic_damage' => false, 'shield' => true, 'heals' => true, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => true, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 6, 'is_good_against_shield' => 7, 'is_good_against_heals' => 8, 'is_good_against_tanky' => 6, 'is_good_against_squish' => 5, 'is_good_against_has_cc' => 4, 'is_good_against_dash' => 8, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 3, 'is_good_against_late_game' => 7, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/7/79/Shurelya%27s_Battlesong_item.png"]);

        Item::firstOrCreate(['name' => "Sterak's Gage", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => true, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 5, 'is_good_against_shield' => 9, 'is_good_against_heals' => 5, 'is_good_against_tanky' => 9, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 4, 'is_good_against_dash' => 3, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 5, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/1/1a/Sterak%27s_Gage_item.png"]);

        Item::firstOrCreate(['name' => "Stormrazor", 'role' => "adc", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => true, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 4, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 6, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 4, 'is_good_against_poke' => 8, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/e/e5/Stormrazor_item.png"]);

        Item::firstOrCreate(['name' => "Sunfire Aegis", 'role' => "tank", 'attack_damage' => true, 'magic_damage' => false, 'shield' => true, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => true, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 6, 'is_good_against_shield' => 9, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 9, 'is_good_against_squish' => 5, 'is_good_against_has_cc' => 7, 'is_good_against_dash' => 3, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/7/7d/Sunfire_Aegis_item.png"]);

        Item::firstOrCreate(['name' => "Titanic Hydra", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => true, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 4, 'is_good_against_shield' => 5, 'is_good_against_heals' => 6, 'is_good_against_tanky' => 8, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 4, 'is_good_against_dash' => 3, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/0/0b/Titanic_Hydra_item.png"]);

        Item::firstOrCreate(['name' => "Trinity Force", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => true, 'tanky' => false, 'squishy' => false, 'has_cc' => false, 'dash' => true, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 5, 'is_good_against_heals' => 6, 'is_good_against_tanky' => 7, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 5, 'is_good_against_dash' => 7, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 5, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/6/6e/Trinity_Force_item.png"]);

        Item::firstOrCreate(['name' => "Chempunk Chainsword", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => true, 'dash' => false, 'poke' => true, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 5, 'is_good_against_shield' => 6, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 6, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 7, 'is_good_against_dash' => 5, 'is_good_against_poke' => 6, 'is_good_against_can_one_shot' => 5, 'is_good_against_late_game' => 7, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/c/cf/Chempunk_Chainsword_item.png"]);

        Item::firstOrCreate(['name' => "Cosmic Drive", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => true, 'poke' => true, 'can_one_shot' => true, 'late_game' => true, 'is_good_against_attack_damage' => 5, 'is_good_against_magic_damage' => 9, 'is_good_against_shield' => 4, 'is_good_against_heals' => 5, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 7, 'is_good_against_poke' => 8, 'is_good_against_can_one_shot' => 7, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/6/6f/Cosmic_Drive_item.png"]);

        Item::firstOrCreate(['name' => "Demonic Embrace", 'role' => "fighter", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 8, 'is_good_against_shield' => 5, 'is_good_against_heals' => 6, 'is_good_against_tanky' => 8, 'is_good_against_squish' => 5, 'is_good_against_has_cc' => 4, 'is_good_against_dash' => 3, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/3/32/Demonic_Embrace_item.png"]);

        Item::firstOrCreate(['name' => "Divine Sunderer", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => true, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 6, 'is_good_against_heals' => 7, 'is_good_against_tanky' => 8, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 4, 'is_good_against_dash' => 4, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 5, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/3/38/Divine_Sunderer_item.png"]);

        Item::firstOrCreate(['name' => "Duskblade of Draktharr", 'role' => "assasin", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => true, 'dash' => true, 'poke' => false, 'can_one_shot' => true, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 2, 'is_good_against_shield' => 5, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 9, 'is_good_against_has_cc' => 6, 'is_good_against_dash' => 8, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 9, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/9/97/Duskblade_of_Draktharr_item.png"]);

        Item::firstOrCreate(['name' => "Edge of Night", 'role' => "assasin", 'attack_damage' => true, 'magic_damage' => false, 'shield' => true, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => true, 'poke' => false, 'can_one_shot' => true, 'late_game' => true, 'is_good_against_attack_damage' => 6, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 7, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 8, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 7, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 8, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/4/49/Edge_of_Night_item.png"]);

        Item::firstOrCreate(['name' => "Evenshroud", 'role' => "tank", 'attack_damage' => false, 'magic_damage' => false, 'shield' => true, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => true, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 5, 'is_good_against_shield' => 9, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 9, 'is_good_against_squish' => 4, 'is_good_against_has_cc' => 7, 'is_good_against_dash' => 3, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/a/a1/Evenshroud_item.png"]);

        Item::firstOrCreate(['name' => "Fimbulwinter", 'role' => "tank", 'attack_damage' => false, 'magic_damage' => false, 'shield' => true, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => true, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 6, 'is_good_against_shield' => 9, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 9, 'is_good_against_squish' => 5, 'is_good_against_has_cc' => 8, 'is_good_against_dash' => 3, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/4/49/Fimbulwinter_item.png"]);

        Item::firstOrCreate(['name' => "Gargoyle Stoneplate", 'role' => "tank", 'attack_damage' => false, 'magic_damage' => false, 'shield' => true, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 9, 'is_good_against_magic_damage' => 9, 'is_good_against_shield' => 10, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 10, 'is_good_against_squish' => 4, 'is_good_against_has_cc' => 4, 'is_good_against_dash' => 3, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/1/15/Gargoyle_Stoneplate_item.png"]);

        Item::firstOrCreate(['name' => "Glorious Enchant", 'role' => "supp", 'attack_damage' => false, 'magic_damage' => false, 'shield' => true, 'heals' => true, 'tanky' => false, 'squishy' => true, 'has_cc' => true, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => false, 'is_good_against_attack_damage' => 5, 'is_good_against_magic_damage' => 5, 'is_good_against_shield' => 7, 'is_good_against_heals' => 8, 'is_good_against_tanky' => 4, 'is_good_against_squish' => 5, 'is_good_against_has_cc' => 7, 'is_good_against_dash' => 3, 'is_good_against_poke' => 4, 'is_good_against_can_one_shot' => 3, 'is_good_against_late_game' => 6, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/f/f5/Glorious_Enchant_item.png"]);

        Item::firstOrCreate(['name' => "Goredrinker", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => true, 'tanky' => true, 'squishy' => false, 'has_cc' => true, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 4, 'is_good_against_shield' => 6, 'is_good_against_heals' => 8, 'is_good_against_tanky' => 8, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 6, 'is_good_against_dash' => 5, 'is_good_against_poke' => 4, 'is_good_against_can_one_shot' => 5, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/f/f1/Goredrinker_item.png"]);

        Item::firstOrCreate(['name' => "Guinsoo's Rageblade", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 7, 'is_good_against_shield' => 5, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 3, 'is_good_against_poke' => 4, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/0/0f/Guinsoo%27s_Rageblade_item.png"]);

        Item::firstOrCreate(['name' => "Hextech Rocketbelt", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => true, 'dash' => true, 'poke' => true, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 5, 'is_good_against_magic_damage' => 9, 'is_good_against_shield' => 5, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 6, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 6, 'is_good_against_dash' => 7, 'is_good_against_poke' => 7, 'is_good_against_can_one_shot' => 5, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/5/59/Hextech_Rocketbelt_item.png"]);

        Item::firstOrCreate(['name' => "Horizon Focus", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => true, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 4, 'is_good_against_magic_damage' => 9, 'is_good_against_shield' => 5, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 2, 'is_good_against_poke' => 8, 'is_good_against_can_one_shot' => 6, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/5/5e/Horizon_Focus_item.png"]);

        Item::firstOrCreate(['name' => "Immortal Shieldbow", 'role' => "adc", 'attack_damage' => true, 'magic_damage' => false, 'shield' => true, 'heals' => true, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => true, 'poke' => false, 'can_one_shot' => true, 'late_game' => true, 'is_good_against_attack_damage' => 6, 'is_good_against_magic_damage' => 4, 'is_good_against_shield' => 7, 'is_good_against_heals' => 8, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 9, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 7, 'is_good_against_poke' => 4, 'is_good_against_can_one_shot' => 9, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/e/e4/Immortal_Shieldbow_item.png"]);

        Item::firstOrCreate(['name' => "Infinity Edge", 'role' => "adc", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => true, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 5, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 9, 'is_good_against_has_cc' => 2, 'is_good_against_dash' => 3, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 10, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/f/f1/Infinity_Edge_item.png"]);

        Item::firstOrCreate(['name' => "Kraken Slayer", 'role' => "adc", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => true, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 6, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 9, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 3, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 9, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/8/8b/Kraken_Slayer_item.png"]);

        Item::firstOrCreate(['name' => "Liandry's Anguish", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => true, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 5, 'is_good_against_magic_damage' => 9, 'is_good_against_shield' => 6, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 6, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 2, 'is_good_against_poke' => 7, 'is_good_against_can_one_shot' => 5, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/7/7a/Liandry%27s_Anguish_item.png"]);

        Item::firstOrCreate(['name' => "Lich Bane", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => true, 'can_one_shot' => true, 'late_game' => true, 'is_good_against_attack_damage' => 4, 'is_good_against_magic_damage' => 8, 'is_good_against_shield' => 4, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 8, 'is_good_against_has_cc' => 2, 'is_good_against_dash' => 3, 'is_good_against_poke' => 6, 'is_good_against_can_one_shot' => 8, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/9/9e/Lich_Bane_item.png"]);

        Item::firstOrCreate(['name' => "Locket of the Iron Solari", 'role' => "supp", 'attack_damage' => false, 'magic_damage' => false, 'shield' => true, 'heals' => true, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 8, 'is_good_against_shield' => 10, 'is_good_against_heals' => 9, 'is_good_against_tanky' => 8, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 6, 'is_good_against_dash' => 3, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 2, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/7/75/Locket_of_the_Iron_Solari_item.png"]);

        Item::firstOrCreate(['name' => "Lord Dominik's Regards", 'role' => "adc", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 4, 'is_good_against_shield' => 9, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 9, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 3, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/1/19/Lord_Dominik%27s_Regards_item.png"]);

        Item::firstOrCreate(['name' => "Luden's Tempest", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => true, 'dash' => true, 'poke' => true, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 5, 'is_good_against_magic_damage' => 9, 'is_good_against_shield' => 5, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 6, 'is_good_against_squish' => 8, 'is_good_against_has_cc' => 6, 'is_good_against_dash' => 7, 'is_good_against_poke' => 8, 'is_good_against_can_one_shot' => 6, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/6/6a/Luden%27s_Tempest_item.png"]);

        Item::firstOrCreate(['name' => "Manamune", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 6, 'is_good_against_magic_damage' => 5, 'is_good_against_shield' => 5, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 3, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 2, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/5/53/Manamune_item.png"]);

        Item::firstOrCreate(['name' => "Maw of Malmortius", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => true, 'shield' => true, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 7, 'is_good_against_shield' => 8, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 2, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 5, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/5/5e/Maw_of_Malmortius_item.png"]);

        Item::firstOrCreate(['name' => "Nashor's Tooth", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => true, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 6, 'is_good_against_magic_damage' => 8, 'is_good_against_shield' => 5, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 4, 'is_good_against_squish' => 8, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 3, 'is_good_against_poke' => 7, 'is_good_against_can_one_shot' => 5, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/8/81/Nashor%27s_Tooth_item.png"]);

        Item::firstOrCreate(['name' => "Naval Commander's Cutlass", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => true, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => false, 'is_good_against_attack_damage' => 5, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 4, 'is_good_against_heals' => 7, 'is_good_against_tanky' => 3, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 2, 'is_good_against_dash' => 2, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 3, 'is_good_against_late_game' => 3, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/e/e7/Naval_Commander%27s_Cutlass_item.png"]);

        Item::firstOrCreate(['name' => "Oblivion Orb", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => false, 'is_good_against_attack_damage' => 3, 'is_good_against_magic_damage' => 7, 'is_good_against_shield' => 4, 'is_good_against_heals' => 5, 'is_good_against_tanky' => 3, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 2, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 3, 'is_good_against_late_game' => 4, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/1/1b/Oblivion_Orb_item.png"]);

        Item::firstOrCreate(['name' => "Obsidian Cleaver", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => true, 'dash' => true, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 6, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 8, 'is_good_against_squish' => 5, 'is_good_against_has_cc' => 7, 'is_good_against_dash' => 5, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/e/e5/Obsidian_Cleaver_item.png"]);

        Item::firstOrCreate(['name' => "Oracle Lens", 'role' => "supp", 'attack_damage' => false, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => true, 'poke' => false, 'can_one_shot' => false, 'late_game' => false, 'is_good_against_attack_damage' => 3, 'is_good_against_magic_damage' => 4, 'is_good_against_shield' => 2, 'is_good_against_heals' => 2, 'is_good_against_tanky' => 2, 'is_good_against_squish' => 4, 'is_good_against_has_cc' => 4, 'is_good_against_dash' => 5, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 3, 'is_good_against_late_game' => 3, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/4/4c/Oracle_Lens_item.png"]);

        Item::firstOrCreate(['name' => "Phantom Dancer", 'role' => "adc", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => true, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 4, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 7, 'is_good_against_poke' => 4, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/5/57/Phantom_Dancer_item.png"]);

        Item::firstOrCreate(['name' => "Rabadon's Deathcap", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => true, 'late_game' => true, 'is_good_against_attack_damage' => 2, 'is_good_against_magic_damage' => 10, 'is_good_against_shield' => 3, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 3, 'is_good_against_squish' => 9, 'is_good_against_has_cc' => 2, 'is_good_against_dash' => 1, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 10, 'is_good_against_late_game' => 10, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/9/9b/Rabadon%27s_Deathcap_item.png"]);

        Item::firstOrCreate(['name' => "Randuin's Omen", 'role' => "tank", 'attack_damage' => false, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => true, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 9, 'is_good_against_magic_damage' => 4, 'is_good_against_shield' => 5, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 9, 'is_good_against_squish' => 5, 'is_good_against_has_cc' => 6, 'is_good_against_dash' => 3, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 3, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/3/34/Randuin%27s_Omen_item.png"]);

        Item::firstOrCreate(['name' => "Ravenous Hydra", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => true, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 5, 'is_good_against_heals' => 7, 'is_good_against_tanky' => 4, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 2, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 3, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/c/cd/Ravenous_Hydra_item.png"]);

        Item::firstOrCreate(['name' => "Refillable Potion", 'role' => "all", 'attack_damage' => false, 'magic_damage' => false, 'shield' => false, 'heals' => true, 'tanky' => false, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => false, 'is_good_against_attack_damage' => 0, 'is_good_against_magic_damage' => 0, 'is_good_against_shield' => 0, 'is_good_against_heals' => 8, 'is_good_against_tanky' => 0, 'is_good_against_squish' => 0, 'is_good_against_has_cc' => 0, 'is_good_against_dash' => 0, 'is_good_against_poke' => 0, 'is_good_against_can_one_shot' => 0, 'is_good_against_late_game' => 0, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/d/dd/Refillable_Potion_item.png"]);

        Item::firstOrCreate(['name' => "Riftmaker", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => true, 'heals' => true, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => true, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 8, 'is_good_against_shield' => 6, 'is_good_against_heals' => 7, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 4, 'is_good_against_dash' => 3, 'is_good_against_poke' => 6, 'is_good_against_can_one_shot' => 5, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/f/fd/Riftmaker_item.png"]);

        Item::firstOrCreate(['name' => "Ruby Crystal", 'role' => "tank", 'attack_damage' => false, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => false, 'is_good_against_attack_damage' => 6, 'is_good_against_magic_damage' => 6, 'is_good_against_shield' => 5, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 7, 'is_good_against_squish' => 3, 'is_good_against_has_cc' => 2, 'is_good_against_dash' => 1, 'is_good_against_poke' => 1, 'is_good_against_can_one_shot' => 1, 'is_good_against_late_game' => 5, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/f/f0/Ruby_Crystal_item.png"]);

        Item::firstOrCreate(['name' => "Runaan's Hurricane", 'role' => "adc", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => true, 'dash' => false, 'poke' => true, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 4, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 6, 'is_good_against_dash' => 4, 'is_good_against_poke' => 6, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/7/7a/Runaan%27s_Hurricane_item.png"]);

        Item::firstOrCreate(['name' => "Rylai's Crystal Scepter", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => true, 'dash' => false, 'poke' => true, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 6, 'is_good_against_magic_damage' => 8, 'is_good_against_shield' => 6, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 7, 'is_good_against_squish' => 5, 'is_good_against_has_cc' => 7, 'is_good_against_dash' => 4, 'is_good_against_poke' => 6, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/1/12/Rylai%27s_Crystal_Scepter_item.png"]);

        Item::firstOrCreate(['name' => "Seraph's Embrace", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => true, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 5, 'is_good_against_magic_damage' => 9, 'is_good_against_shield' => 7, 'is_good_against_heals' => 4, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 3, 'is_good_against_poke' => 4, 'is_good_against_can_one_shot' => 4, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/2/27/Seraph%27s_Embrace_item.png"]);

        Item::firstOrCreate(['name' => "Serpent's Fang", 'role' => "assasin", 'attack_damage' => true, 'magic_damage' => false, 'shield' => true, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => true, 'poke' => false, 'can_one_shot' => true, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 9, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 8, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 7, 'is_good_against_poke' => 3, 'is_good_against_can_one_shot' => 9, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/8/85/Serpent%27s_Fang_item.png"]);

        Item::firstOrCreate(['name' => "Spectre's Cowl", 'role' => "tank", 'attack_damage' => false, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => false, 'is_good_against_attack_damage' => 4, 'is_good_against_magic_damage' => 7, 'is_good_against_shield' => 3, 'is_good_against_heals' => 1, 'is_good_against_tanky' => 6, 'is_good_against_squish' => 3, 'is_good_against_has_cc' => 2, 'is_good_against_dash' => 1, 'is_good_against_poke' => 1, 'is_good_against_can_one_shot' => 1, 'is_good_against_late_game' => 3, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/6/60/Spectre%27s_Cowl_item.png"]);

        Item::firstOrCreate(['name' => "Spirit Visage", 'role' => "tank", 'attack_damage' => false, 'magic_damage' => false, 'shield' => false, 'heals' => true, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 6, 'is_good_against_magic_damage' => 8, 'is_good_against_shield' => 4, 'is_good_against_heals' => 9, 'is_good_against_tanky' => 7, 'is_good_against_squish' => 4, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 2, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 1, 'is_good_against_late_game' => 7, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/c/c3/Spirit_Visage_item.png"]);

        Item::firstOrCreate(['name' => "Stalker's Blade", 'role' => "jungler", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => false, 'has_cc' => false, 'dash' => true, 'poke' => false, 'can_one_shot' => false, 'late_game' => false, 'is_good_against_attack_damage' => 6, 'is_good_against_magic_damage' => 2, 'is_good_against_shield' => 3, 'is_good_against_heals' => 2, 'is_good_against_tanky' => 3, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 2, 'is_good_against_dash' => 7, 'is_good_against_poke' => 1, 'is_good_against_can_one_shot' => 2, 'is_good_against_late_game' => 3, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/e/e2/Stalker's_Blade_item.png"]);

        Item::firstOrCreate(['name' => "Stinger", 'role' => "jungler", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => false, 'is_good_against_attack_damage' => 5, 'is_good_against_magic_damage' => 2, 'is_good_against_shield' => 2, 'is_good_against_heals' => 1, 'is_good_against_tanky' => 3, 'is_good_against_squish' => 4, 'is_good_against_has_cc' => 2, 'is_good_against_dash' => 1, 'is_good_against_poke' => 1, 'is_good_against_can_one_shot' => 1, 'is_good_against_late_game' => 2, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/3/32/Stinger_item.png"]);

        Item::firstOrCreate(['name' => "Sterak's Gage", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => true, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 9, 'is_good_against_magic_damage' => 2, 'is_good_against_shield' => 9, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 9, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 1, 'is_good_against_dash' => 2, 'is_good_against_poke' => 1, 'is_good_against_can_one_shot' => 3, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/e/e0/Sterak%27s_Gage_item.png"]);

        Item::firstOrCreate(['name' => "Sunfire Aegis", 'role' => "tank", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 9, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 3, 'is_good_against_heals' => 2, 'is_good_against_tanky' => 9, 'is_good_against_squish' => 4, 'is_good_against_has_cc' => 2, 'is_good_against_dash' => 1, 'is_good_against_poke' => 1, 'is_good_against_can_one_shot' => 1, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/5/5f/Sunfire_Aegis_item.png"]);

        Item::firstOrCreate(['name' => "Thornmail", 'role' => "tank", 'attack_damage' => false, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 9, 'is_good_against_magic_damage' => 2, 'is_good_against_shield' => 8, 'is_good_against_heals' => 1, 'is_good_against_tanky' => 9, 'is_good_against_squish' => 3, 'is_good_against_has_cc' => 1, 'is_good_against_dash' => 1, 'is_good_against_poke' => 1, 'is_good_against_can_one_shot' => 1, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/5/5b/Thornmail_item.png"]);

        Item::firstOrCreate(['name' => "Titanic Hydra", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => true, 'squishy' => false, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 9, 'is_good_against_magic_damage' => 2, 'is_good_against_shield' => 5, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 8, 'is_good_against_squish' => 6, 'is_good_against_has_cc' => 2, 'is_good_against_dash' => 3, 'is_good_against_poke' => 1, 'is_good_against_can_one_shot' => 3, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/5/55/Titanic_Hydra_item.png"]);

        Item::firstOrCreate(['name' => "Trinity Force", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => true, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 8, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 3, 'is_good_against_heals' => 2, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 2, 'is_good_against_dash' => 7, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 3, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/6/6d/Trinity_Force_item.png"]);

        Item::firstOrCreate(['name' => "Umbral Glaive", 'role'=>"assasin", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => true, 'poke' => false, 'can_one_shot' => true, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 2, 'is_good_against_shield' => 6, 'is_good_against_heals' => 2, 'is_good_against_tanky' => 5, 'is_good_against_squish' => 8, 'is_good_against_has_cc' => 3, 'is_good_against_dash' => 8, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 9, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/f/fb/Umbral_Glaive_item.png"]);

        Item::firstOrCreate(['name' => "Void Staff", 'role' => "mage", 'attack_damage' => false, 'magic_damage' => true, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => true, 'late_game' => true, 'is_good_against_attack_damage' => 3, 'is_good_against_magic_damage' => 8, 'is_good_against_shield' => 3, 'is_good_against_heals' => 3, 'is_good_against_tanky' => 3, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 1, 'is_good_against_dash' => 2, 'is_good_against_poke' => 1, 'is_good_against_can_one_shot' => 9, 'is_good_against_late_game' => 9, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/2/2f/Void_Staff_item.png"]);

        Item::firstOrCreate(['name' => "Wit's End", 'role' => "fighter", 'attack_damage' => true, 'magic_damage' => false, 'shield' => false, 'heals' => false, 'tanky' => false, 'squishy' => true, 'has_cc' => false, 'dash' => false, 'poke' => false, 'can_one_shot' => false, 'late_game' => true, 'is_good_against_attack_damage' => 7, 'is_good_against_magic_damage' => 3, 'is_good_against_shield' => 3, 'is_good_against_heals' => 2, 'is_good_against_tanky' => 6, 'is_good_against_squish' => 7, 'is_good_against_has_cc' => 1, 'is_good_against_dash' => 1, 'is_good_against_poke' => 2, 'is_good_against_can_one_shot' => 3, 'is_good_against_late_game' => 8, 'photo' => "https://static.wikia.nocookie.net/leagueoflegends/images/7/75/Wit's_End_item.png"]);

    }
}
